name: chess_game_poc

on: 
  push: 
    branches:
      - master 
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9","3.10","3.11","3.12","3.13"]

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build the Docker image
      run: docker build -t chess_game_poc .

    - name: Run code linting with ruff
      run: docker run --rm chess_game_poc make lint

    - name: Run the tests in Docker container
      run: docker run --rm chess_game_poc make tests